name: RaboIssueParser tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    run_tests:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app && /usr/bin/xcodebuild -version
      - name: Run tests
        run: xcodebuild test -scheme RaboIssueParser -workspace RaboIssueParser.xcworkspace -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 13' | xcpretty && exit ${PIPESTATUS[0]}
