name: RaboIssueParser tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    run_tests:
      name: ${{ matrix.command }} on  ${{ matrix.platform }} (xcode ${{ matrix.xcode }}, ${{ matrix.macos }})
      runs-on: ${{ matrix.macos }} #os switching
      strategy:
        fail-fast: false #if 'true' then one failed job cancels all jobs remaining
        matrix:
          xcode: ['13.2.1', '12.5.1']
          macos: ['macos-latest']
          scheme: ['RaboIssueParser']
          command: ['test']
      steps:
      - uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app && /usr/bin/xcodebuild -version
      - name: Run tests
        run: xcodebuild ${{ matrix.command }} -scheme ${{ matrix.scheme }} -workspace RaboIssueParser.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 12 Pro' | xcpretty && exit ${PIPESTATUS[0]}
