name: RaboIssueParser tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    run_tests:
      name: ${{ matrix.command }} on  ${{ matrix.platform }} (xcode ${{ matrix.xcode }}, ${{ matrix.macos }})
      runs-on: ${{ matrix.macos }} #os switching
      strategy:
        fail-fast: false #if 'true' then one failed job cancels all jobs remaining
        matrix:
          xcode: ['13.2.1', '12.5.1']
          macos: ['macos-latest']
          scheme: ['RaboIssueParser']
          command: ['test']
          platform: ['iOS']
      steps:
      - uses: maxim-lobanov/setup-xcode
        with:
          xcode-version: ${{ matrix.xcode }}
      - uses: mxcl/xcodebuild
        with:
          platform: ${{ matrix.platform }}
          scheme: ${{ matrix.scheme }}
          action: ${{ matrix.command }}
          code-coverage: true
          verbosity: xcpretty
          upload-logs: always
