name: RaboIssueParser tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    run_tests:
      name: ${{ matrix.command }} on  ${{ matrix.platform }} (xcode ${{ matrix.xcode }}, ${{ matrix.macos }})
      runs-on: ${{ matrix.macos }} #os switching
      strategy:
        fail-fast: false #if 'true' then one failed job cancels all jobs remaining
        matrix:
          xcode: ['13.2.1']
          macos: ['macos-latest']
          scheme: ['RaboIssueParser']
          command: ['test']
          os: ['15.2', '14.4']
      steps:
      - uses: actions/checkout@v1
      - name: Prepare iOS 14 simulator
        run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          sudo ln -s /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 14.4.simruntime
          xcrun simctl list runtimes
          xcrun simctl create custom-test-device "iPhone 12 Pro" "com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro" "com.apple.CoreSimulator.SimRuntime.iOS-14-4"
          xcrun simctl list devices 14.4
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app && /usr/bin/xcodebuild -version
      - name: Run tests
        run: xcodebuild ${{ matrix.command }} -scheme ${{ matrix.scheme }} -workspace RaboIssueParser.xcworkspace -destination 'platform=iOS Simulator,OS=${{ matrix.os }},name=iPhone 12 Pro' | xcpretty && exit ${PIPESTATUS[0]}
